# numpy notes
> Notes on numpy

- toc: true
- branch: master
- badges: true
- comments: true
- author: Stephen Zagar
- categories: [numpy, notes]

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [95]:
import random
rnd = random.Random(1234)

for _ in range(10): print(np.random.randint(2,3))
for _ in range(10): print(rnd.randint(2,3))

2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
3
2
2


In [15]:
c = np.arange(10)

In [18]:
c.shape = (5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
c=c.T
c

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [27]:
c.reshape(5,2)

array([[0, 2],
       [4, 6],
       [8, 1],
       [3, 5],
       [7, 9]])

In [28]:
c.flatten()

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [29]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
v = a[1:3,:]

In [50]:
v

array([[ 5,  6, 99,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 99,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
v[0] = 99

In [53]:
v

array([[99, 99, 99, 99, 99],
       [10, 11, 12, 13, 14]])

In [54]:
a

array([[ 0,  1,  2,  3,  4],
       [99, 99, 99, 99, 99],
       [10, 11, 12, 13, 14]])

In [55]:
v[1]

array([10, 11, 12, 13, 14])

In [59]:
v[1][1]

11

In [67]:
a

array([[ 0,  1,  2,  3,  4],
       [99, 99, 99, 99, 99],
       [10, 11, 12, 13, 14]])

In [68]:
m = np.logical_and(a > 12, a < 99)
m

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [69]:
a > 98

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [71]:
a[m] = -5

In [72]:
a

array([[ 0,  1,  2,  3,  4],
       [99, 99, 99, 99, 99],
       [10, 11, 12, -5, -5]])

In [73]:
v

array([[99, 99, 99, 99, 99],
       [10, 11, 12, -5, -5]])

In [74]:
b = np.arange(15).reshape(3, 5)

In [81]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
b[[0,2],:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [84]:
b[[True,False,True],2:4]

array([[ 2,  3],
       [12, 13]])

In [90]:
np.ones(2,str)

array(['1', '1'], dtype='<U1')

In [98]:
cs = np.arange(10)
cs

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
print(cs.cumsum())

[ 0  1  3  6 10 15 21 28 36 45]


In [2]:
import pandas as pd

In [6]:
data = {'Name':['Tom','nick','krish'], 'Age':[20,21,19]}
df = pd.DataFrame(data)
df

Name  Age
0    Tom   20
1   nick   21
2  krish   19

In [9]:
df[['Age']]

Age
0   20
1   21
2   19

In [12]:
df.iloc[0:2]['Age']

0    20
1    21
Name: Age, dtype: int64

In [20]:
df[0:1][['Name','Age']]

Name  Age
0  Tom   20